allprojects {
    repositories {
        google()
        mavenCentral()
    }
    tasks.withType(com.android.build.gradle.internal.tasks.ApplicationIdWriterTask).configureEach {
        enabled = false
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
